# Generated by Django 5.1 on 2024-08-29 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowercategory',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
