# Generated by Django 5.1 on 2024-09-05 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_remove_flower_category_flower_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='category',
        ),
        migrations.AddField(
            model_name='flower',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='flowers.flowercategory'),
        ),
    ]
