# Generated by Django 5.1 on 2025-02-19 19:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0005_remove_flower_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
