# Generated by Django 5.1 on 2025-02-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_alter_flower_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.FileField(upload_to='flowers_image'),
        ),
    ]
