# Generated by Django 5.1 on 2025-02-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0007_alter_flower_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='image',
        ),
        migrations.AddField(
            model_name='flower',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
