# Generated by Django 5.1 on 2025-02-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_account_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.AddField(
            model_name='account',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
