# Generated by Django 5.1 on 2025-02-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_account_image_account_image_url'),
    ]

    operations = [
    ]
