# Generated by Django 5.1 on 2025-02-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20250220_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image_url',
        ),
    ]
