# Generated by Django 5.1 on 2024-10-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_flower_remove_order_quantity_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
