# Generated by Django 5.1 on 2024-10-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_items_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
