# Generated by Django 5.1 on 2024-10-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_items_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_amount',
            field=models.FloatField(default=0),
        ),
    ]
