# Generated by Django 5.1 on 2024-10-30 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_cart_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_amount',
        ),
    ]
