# Generated by Django 5.1.3 on 2024-11-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_cart_grand_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_image',
            field=models.ImageField(blank=True, null=True, upload_to='cart_images/'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_at_added',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
