# Generated by Django 5.1.3 on 2024-11-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_cartitem_cart_image_cartitem_price_at_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
